// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKTX9smVMzdw78FzaFupS7NxcBKvuYHAE',
    appId: '1:775678673132:web:5ecc56b5917837213325c9',
    messagingSenderId: '775678673132',
    projectId: 'aqarhub',
    authDomain: 'aqarhub.firebaseapp.com',
    storageBucket: 'aqarhub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlKx7jrg6Nn32qwNt_tUBxv0G5WTgclA4',
    appId: '1:775678673132:android:8eb486714befce123325c9',
    messagingSenderId: '775678673132',
    projectId: 'aqarhub',
    storageBucket: 'aqarhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FYj5hTzzOi7YFdoVXJ7GhF6KAYTPso8',
    appId: '1:775678673132:ios:759e5017f179eaa83325c9',
    messagingSenderId: '775678673132',
    projectId: 'aqarhub',
    storageBucket: 'aqarhub.firebasestorage.app',
    iosBundleId: 'com.example.aqarHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FYj5hTzzOi7YFdoVXJ7GhF6KAYTPso8',
    appId: '1:775678673132:ios:759e5017f179eaa83325c9',
    messagingSenderId: '775678673132',
    projectId: 'aqarhub',
    storageBucket: 'aqarhub.firebasestorage.app',
    iosBundleId: 'com.example.aqarHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKTX9smVMzdw78FzaFupS7NxcBKvuYHAE',
    appId: '1:775678673132:web:8ab0a33566f72b943325c9',
    messagingSenderId: '775678673132',
    projectId: 'aqarhub',
    authDomain: 'aqarhub.firebaseapp.com',
    storageBucket: 'aqarhub.firebasestorage.app',
  );
}
